const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const PORT=Number(process.env.PORT)||3000;
const ROOT=__dirname,DB_FILE=path.join(ROOT,'data','db.json');
const PRODUCTS=[
{id:1,name:'Écouteurs Bluetooth Pro',category:'Audio',price:12500,oldPrice:16000,badge:'POPULAIRE',rating:4.8,reviews:126,image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1000&q=88',description:'Écouteurs sans fil compacts avec boîtier de charge et connexion Bluetooth.',stock:24},
{id:2,name:'Casque sans fil Studio',category:'Audio',price:28000,oldPrice:35000,badge:'PROMO',rating:4.9,reviews:89,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=88',description:'Casque confortable pour musique, vidéos et appels.',stock:12},
{id:3,name:'Chargeur USB-C rapide',category:'Charge',price:9000,oldPrice:12000,badge:'TOP',rating:4.7,reviews:74,image:'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1000&q=88',description:'Chargeur compact conçu pour la charge rapide des appareils compatibles.',stock:35},
{id:4,name:'Câble USB-C renforcé',category:'Charge',price:4500,oldPrice:6000,badge:'',rating:4.6,reviews:51,image:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1000&q=88',description:'Câble robuste pour charge et transfert de données.',stock:50},
{id:5,name:'Coque smartphone premium',category:'Protection',price:7500,oldPrice:9500,badge:'NOUVEAU',rating:4.8,reviews:63,image:'https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?auto=format&fit=crop&w=1000&q=88',description:'Coque élégante et résistante pour protéger ton smartphone.',stock:28},
{id:6,name:'Verre de protection',category:'Protection',price:3500,oldPrice:4500,badge:'',rating:4.7,reviews:42,image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=88',description:'Protection d’écran fine et transparente.',stock:60},
{id:7,name:'Hub USB multiports',category:'Connectivité',price:18500,oldPrice:22000,badge:'PROMO',rating:4.7,reviews:38,image:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1000&q=88',description:'Étends les ports de ton ordinateur avec plusieurs connexions USB.',stock:15},
{id:8,name:'Adaptateur Bluetooth',category:'Connectivité',price:11000,oldPrice:14000,badge:'',rating:4.6,reviews:29,image:'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=1000&q=88',description:'Ajoute facilement la connectivité Bluetooth aux appareils compatibles.',stock:19}
];
function ensure(){if(!fs.existsSync(path.dirname(DB_FILE)))fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify({users:[],orders:[],reviews:[],newsletter:[]},null,2));}
function db(){ensure();return JSON.parse(fs.readFileSync(DB_FILE,'utf8'));}function save(x){fs.writeFileSync(DB_FILE,JSON.stringify(x,null,2));}function uid(){return crypto.randomUUID();}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {salt:s,hash:crypto.scryptSync(p,s,64).toString('hex')}}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Headers':'Content-Type',...headers});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(new Error('JSON invalide'))}});req.on('error',reject)})}
function product(id){return PRODUCTS.find(p=>p.id===Number(id));}
function mime(p){return {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8'}[path.extname(p).toLowerCase()]||'application/octet-stream';}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');
if(req.method==='OPTIONS')return send(res,204,{});
if(req.method==='GET'&&u.pathname==='/api/products')return send(res,200,PRODUCTS);
if(req.method==='GET'&&u.pathname==='/api/products/'+u.pathname.split('/').pop()){const p=product(u.pathname.split('/').pop());return p?send(res,200,p):send(res,404,{error:'Produit introuvable'});}
if(req.method==='POST'&&u.pathname==='/api/auth/register'){const x=await body(req),d=db(),name=String(x.name||'').trim(),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');if(name.length<2||!email.includes('@')||password.length<6)return send(res,400,{error:'Nom, email ou mot de passe invalide.'});if(d.users.some(a=>a.email===email))return send(res,409,{error:'Cet email est déjà utilisé.'});const h=hash(password);const user={id:uid(),name,email,passwordHash:h.hash,salt:h.salt,createdAt:new Date().toISOString()};d.users.push(user);save(d);return send(res,201,{user:{id:user.id,name:user.name,email:user.email},message:'Compte créé avec succès.'});}
if(req.method==='POST'&&u.pathname==='/api/auth/login'){const x=await body(req),d=db(),email=String(x.email||'').trim().toLowerCase(),u1=d.users.find(a=>a.email===email);if(!u1)return send(res,401,{error:'Email ou mot de passe incorrect.'});const h=hash(String(x.password||''),u1.salt);if(h.hash!==u1.passwordHash)return send(res,401,{error:'Email ou mot de passe incorrect.'});return send(res,200,{user:{id:u1.id,name:u1.name,email:u1.email}});}
if(req.method==='POST'&&u.pathname==='/api/newsletter'){const x=await body(req),d=db(),email=String(x.email||'').trim().toLowerCase();if(!email.includes('@'))return send(res,400,{error:'Email invalide.'});if(!d.newsletter.includes(email))d.newsletter.push(email);save(d);return send(res,201,{message:'Inscription enregistrée.'});}
if(req.method==='POST'&&u.pathname==='/api/orders'){const x=await body(req),d=db(),items=[],total=0;for(const i of Array.isArray(x.items)?x.items:[]){const p=product(i.id),qty=Math.max(1,Math.min(99,Number(i.qty)||1));if(p){items.push({productId:p.id,name:p.name,qty,unitPrice:p.price});}}
if(!items.length)return send(res,400,{error:'Panier vide.'});for(const i of items)i.lineTotal=i.qty*i.unitPrice;const sum=items.reduce((a,i)=>a+i.lineTotal,0);const o={id:uid(),customer:x.customer||{},items,total:sum,status:'pending',payment:null,createdAt:new Date().toISOString()};d.orders.push(o);save(d);return send(res,201,{orderId:o.id,total:sum,status:o.status});}
if(req.method==='GET'&&u.pathname==='/api/orders'){const d=db(),email=String(u.searchParams.get('email')||'').trim().toLowerCase();return send(res,200,d.orders.filter(o=>String(o.customer?.email||'').toLowerCase()===email).reverse());}
if(req.method==='POST'&&u.pathname==='/api/payments/start'){const x=await body(req),d=db(),o=d.orders.find(a=>a.id===x.orderId);if(!o)return send(res,404,{error:'Commande introuvable.'});const provider=String(x.provider||'').toLowerCase();if(!['orange','mtn'].includes(provider))return send(res,400,{error:'Choisis Orange Money ou MTN MoMo.'});o.payment={provider,status:'test_pending',transactionId:'TEST-'+uid(),createdAt:new Date().toISOString()};save(d);return send(res,200,{ok:true,mode:'test',message:`Paiement ${provider==='orange'?'Orange Money':'MTN MoMo'} simulé. Aucun argent réel n'a été débité.`,transactionId:o.payment.transactionId});}
if(req.method==='POST'&&u.pathname==='/api/reviews'){const x=await body(req),d=db(),p=product(x.productId),rating=Math.max(1,Math.min(5,Number(x.rating)||5)),text=String(x.text||'').trim();if(!p||!text)return send(res,400,{error:'Avis invalide.'});const r={id:uid(),productId:p.id,name:String(x.name||'Client'),rating,text,createdAt:new Date().toISOString()};d.reviews.push(r);save(d);return send(res,201,{review:r});}
if(req.method==='GET'&&u.pathname==='/api/reviews'){const d=db(),pid=Number(u.searchParams.get('productId'));return send(res,200,d.reviews.filter(r=>r.productId===pid).reverse());}
if(req.method==='GET'&&u.pathname==='/api/admin/summary'){const d=db();return send(res,200,{users:d.users.length,orders:d.orders.length,pending:d.orders.filter(o=>o.status==='pending').length,revenue:d.orders.filter(o=>o.status==='paid').reduce((s,o)=>s+o.total,0),newsletter:d.newsletter.length});}
if(req.method==='GET'&&u.pathname==='/api/admin/orders')return send(res,200,db().orders.slice().reverse());
if(req.method==='PATCH'&&u.pathname.startsWith('/api/admin/orders/')){const oid=decodeURIComponent(u.pathname.split('/').pop()),x=await body(req),d=db(),o=d.orders.find(a=>a.id===oid);if(!o)return send(res,404,{error:'Commande introuvable.'});const allowed=['pending','processing','shipped','completed','paid','cancelled'];if(!allowed.includes(x.status))return send(res,400,{error:'Statut invalide.'});o.status=x.status;o.updatedAt=new Date().toISOString();save(d);return send(res,200,{order:o});}
// Static root is flat: site.html, site.css, site.js and admin/.
let rel=u.pathname==='/'?'site.html':decodeURIComponent(u.pathname.slice(1));const safeRoot=path.resolve(ROOT),file=path.resolve(ROOT,rel);if(!file.startsWith(safeRoot+path.sep))return send(res,403,{error:'Accès refusé.'});if(fs.existsSync(file)&&fs.statSync(file).isFile()){res.writeHead(200,{'Content-Type':mime(file),'Cache-Control':'no-cache'});return fs.createReadStream(file).pipe(res);}return send(res,404,{error:'Ressource introuvable.'});
}catch(e){console.error(e);return send(res,500,{error:'Erreur serveur.'});}});
server.listen(PORT,()=>console.log(`Califa Shop: http://localhost:${PORT}`));
