const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
let PRODUCTS=[],cart=JSON.parse(localStorage.getItem('califa_cart')||'[]'),favorites=JSON.parse(localStorage.getItem('califa_favorites')||'[]'),filter='Tous',query='',authMode='login',currentOrderId=null,currentProvider='orange';
const state={user:JSON.parse(localStorage.getItem('califa_user')||'null')};
function saveCart(){localStorage.setItem('califa_cart',JSON.stringify(cart));}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2400)}
function notify(t){$('#notificationText').textContent=t;$('#notification').classList.add('show');clearTimeout(window.__note);window.__note=setTimeout(()=>$('#notification').classList.remove('show'),5000)}
function openModal(id){$('#'+id).classList.remove('hidden');document.body.classList.add('no-scroll')}
function closeModal(id){$('#'+id).classList.add('hidden');if(!$$('.modal:not(.hidden)').length)document.body.classList.remove('no-scroll')}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Erreur serveur');return d}
async function loadProducts(){try{PRODUCTS=await api('/api/products');renderProducts();renderCart();}catch(e){toast('Impossible de charger les produits : '+e.message)}}
function filtered(){let a=PRODUCTS.filter(p=>filter==='Tous'||p.category===filter);if(query)a=a.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(query.toLowerCase()));const s=$('#sortSelect').value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);if(s==='name')a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function renderProducts(){const a=filtered();$('#resultCount').textContent=`${a.length} produit${a.length>1?'s':''}`;$('#emptyProducts').classList.toggle('hidden',a.length!==0);$('#productGrid').innerHTML=a.map(p=>{const fav=favorites.includes(p.id);return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.style.opacity='.25'"><span class="badge">${p.badge||'CALIFA'}</span><button class="heart ${fav?'liked':''}" data-fav="${p.id}">${fav?'♥':'♡'}</button></div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><div class="stars">★★★★★ <span>${p.rating} (${p.reviews})</span></div><div class="product-bottom"><div><b>${money(p.price)}</b><del>${money(p.oldPrice)}</del></div><div class="product-actions"><button class="quick-btn" data-view="${p.id}">Voir</button><button class="add-btn" data-add="${p.id}">Ajouter</button></div></div></div></article>`}).join('')}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0),total=0;$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);if(!p)return '';total+=p.price*x.qty;return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><b>${money(p.price)}</b><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`}).join(''):`<div class="empty">🛒<br><br>Ton panier est vide.</div>`;$('#cartTotal').textContent=money(total)}
function add(id){const p=PRODUCTS.find(p=>p.id===id);if(!p)return;const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});saveCart();renderCart();openCart();toast(`${p.name} ajouté au panier`)}
function change(id,n){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart();renderCart()}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show');document.body.classList.add('no-scroll')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show');document.body.classList.remove('no-scroll')}
function renderAccount(){if(state.user){$('#accountBtn').innerHTML='👤 <span>'+state.user.name.split(' ')[0]+'</span>'}}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;$('#productDetail').innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="${p.name}"><div class="detail-copy"><span class="eyebrow">${p.category.toUpperCase()}</span><h2>${p.name}</h2><div class="stars">★★★★★ <span>${p.rating} • ${p.reviews} avis</span></div><p>${p.description}</p><div class="detail-price">${money(p.price)}</div><del>${money(p.oldPrice)}</del><p>Stock indicatif : ${p.stock} unités.</p><button class="btn primary full" data-detail-add="${p.id}">Ajouter au panier</button><div class="review-box"><b>Donner un avis</b><form id="reviewForm"><label>Note<select id="reviewRating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Commentaire<input id="reviewText" required placeholder="Ton avis sur le produit"></label><button class="btn ghost full">Publier</button></form><div id="reviews"></div></div></div></div>`;openModal('productModal');loadReviews(id)}
async function loadReviews(id){try{const rs=await api('/api/reviews?productId='+id);$('#reviews').innerHTML=rs.length?rs.slice(0,4).map(r=>`<div class="review"><b>${r.name}</b> ${'★'.repeat(r.rating)}<br>${r.text}<br><small>${new Date(r.createdAt).toLocaleDateString('fr-FR')}</small></div>`).join(''):'<p class="form-message">Pas encore d’avis.</p>'}catch{}}
function authForm(){const reg=authMode==='register';$('#authName').parentElement.style.display=reg?'block':'none';$('#authSubmit').textContent=reg?'Créer mon compte':'Se connecter';$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.auth===authMode))}
async function submitAuth(e){e.preventDefault();const payload={name:$('#authName').value,email:$('#authEmail').value,password:$('#authPassword').value};try{const d=await api('/api/auth/'+(authMode==='register'?'register':'login'),{method:'POST',body:JSON.stringify(payload)});if(d.user){state.user=d.user;localStorage.setItem('califa_user',JSON.stringify(d.user));renderAccount()}$('#authMessage').textContent=d.message||'Connexion réussie.';toast(d.message||'Connexion réussie');setTimeout(()=>closeModal('accountModal'),800)}catch(err){$('#authMessage').textContent=err.message}}
async function checkout(e){e.preventDefault();if(!cart.length)return toast('Ton panier est vide.');const customer={name:$('#customerName').value,email:$('#customerEmail').value,phone:$('#customerPhone').value,address:$('#customerAddress').value};try{const d=await api('/api/orders',{method:'POST',body:JSON.stringify({items:cart,customer})});currentOrderId=d.orderId;currentProvider=$('#paymentProvider').value;closeModal('checkoutModal');$('#paymentTitle').textContent=currentProvider==='orange'?'🟠 Orange Money — TEST':'🟡 MTN MoMo — TEST';openModal('paymentModal');toast('Commande créée');}catch(err){toast(err.message)}}
async function pay(){try{const d=await api('/api/payments/start',{method:'POST',body:JSON.stringify({orderId:currentOrderId,provider:currentProvider})});$('#paymentMessage').textContent=d.message+' Référence : '+d.transactionId;cart=[];saveCart();renderCart();notify('Commande enregistrée avec succès.');}catch(e){$('#paymentMessage').textContent=e.message}}
async function loadOrders(e){e.preventDefault();const email=$('#ordersEmail').value.trim();try{const orders=await api('/api/orders?email='+encodeURIComponent(email));$('#ordersList').innerHTML=orders.length?orders.map(o=>`<div class="order-row"><div><b>#${o.id.slice(0,8)}</b><small><br>${o.items.map(i=>i.name+' ×'+i.qty).join(' • ')}<br>${new Date(o.createdAt).toLocaleString('fr-FR')}</small></div><strong>${money(o.total)}</strong><span class="status">${o.status}${o.payment?' • '+o.payment.provider:''}</span></div>`).join(''):'<div class="empty">Aucune commande pour cet email.</div>'}catch(err){toast(err.message)}}
function theme(){const light=document.documentElement.classList.toggle('light');localStorage.setItem('califa_theme',light?'light':'dark');toast(light?'Mode clair activé':'Mode sombre activé')}
$('#productGrid').addEventListener('click',e=>{const a=e.target.closest('[data-add]'),v=e.target.closest('[data-view]'),f=e.target.closest('[data-fav]');if(a)add(+a.dataset.add);if(v)openProduct(+v.dataset.view);if(f){const id=+f.dataset.fav;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('califa_favorites',JSON.stringify(favorites));renderProducts();toast(favorites.includes(id)?'Ajouté aux favoris':'Retiré des favoris')}});
$('#cartItems').addEventListener('click',e=>{const p=e.target.closest('[data-plus]'),m=e.target.closest('[data-minus]'),r=e.target.closest('[data-remove]');if(p)change(+p.dataset.plus,1);if(m)change(+m.dataset.minus,-1);if(r){cart=cart.filter(x=>x.id!==+r.dataset.remove);saveCart();renderCart()}});
$('#productDetail').addEventListener('click',e=>{const b=e.target.closest('[data-detail-add]');if(b)add(+b.dataset.detailAdd)});
$('#productDetail').addEventListener('submit',async e=>{if(e.target.id!=='reviewForm')return;e.preventDefault();const p=$('#productDetail [data-detail-add]').dataset.detailAdd;try{await api('/api/reviews',{method:'POST',body:JSON.stringify({productId:+p,rating:+$('#reviewRating').value,text:$('#reviewText').value,name:state.user?.name||'Client'})});$('#reviewText').value='';toast('Avis publié');loadReviews(+p)}catch(err){toast(err.message)}});
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});
$$('.category-card').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.category;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));renderProducts();$('#boutique').scrollIntoView({behavior:'smooth'})}));
$('#searchInput').addEventListener('input',e=>{query=e.target.value;renderProducts()});$('#searchBtn').addEventListener('click',()=>$('#boutique').scrollIntoView({behavior:'smooth'}));$('#sortSelect').addEventListener('change',renderProducts);
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#accountBtn').onclick=()=>{openModal('accountModal');authForm()};$('#themeBtn').onclick=theme;$('#dealBtn').onclick=()=>{filter='Tous';query='';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='Tous'));renderProducts();$('#boutique').scrollIntoView({behavior:'smooth'})};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');
$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.tab').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;authForm()});$('#authForm').onsubmit=submitAuth;$('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Ton panier est vide');closeCart();$('#customerName').value=state.user?.name||'';$('#customerEmail').value=state.user?.email||'';openModal('checkoutModal')};$('#checkoutForm').onsubmit=checkout;$('#payNow').onclick=pay;$('#ordersForm').onsubmit=loadOrders;
$('#newsletterForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/newsletter',{method:'POST',body:JSON.stringify({email:$('#newsletterEmail').value})});toast(d.message);e.target.reset()}catch(err){toast(err.message)}};$('#notificationClose').onclick=()=>$('#notification').classList.remove('show');
if(localStorage.getItem('califa_theme')==='light')document.documentElement.classList.add('light');authForm();renderAccount();loadProducts();setTimeout(()=>notify('Bienvenue sur Califa Shop 👋'),1000);
